# https://dart.dev/guides/language/analysis-options

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # avoid_print: false
    prefer_single_quotes: true
    prefer_final_locals: true
    sort_constructors_first: true
    use_build_context_synchronously: false
