name: hueman
description: An open-source game about color theory.
publish_to: "none"

version: 2.3.1+16

environment:
  sdk: ^3.7.0-0

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ">=6.2.6"
  rive: ">=0.13.13"
  shared_preferences: ">=2.3.2"
  audioplayers: ">=6.1.0"
  meta: ">=1.15.0"

dev_dependencies:
  flutter_launcher_icons: ">=0.13.1"
  flutter_test:
    sdk: flutter
  rename: ">=3.0.2"
  flutter_lints: ^5.0.0
  msix: ">=3.16.8" # https://pub.dev/packages/msix

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon/iOS_icon.png"
  min_sdk_android: 21
  windows:
    generate: true
    image_path: "assets/app_icon/windows_icon.png"
  macos:
    generate: true
    image_path: "assets/app_icon/mac_icon.png"

msix_config:
  display_name: "HUEman: a game about colors"
  publisher: CN=45439987-713E-4806-A939-727F9EEB2172
  publisher_display_name: Nate Wilson
  identity_name: 56500NateWilson.HUEmanagameaboutcolors
  msix_version: 2.3.0.0 # dart run msix:create
  logo_path: C:\Users\Nate\repos\hueman\assets\app_icon\windows_icon.png
  store: true

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/audio/
    - assets/end_credits_icons/
    - assets/public_domain_photos/
    - assets/

  fonts:
    - family: nunito sans
      fonts:
        - asset: assets/fonts/nunito_sans.ttf
        - asset: assets/fonts/nunito_sans_italic.ttf
          style: italic
    - family: sometype mono
      fonts:
        - asset: assets/fonts/sometype_mono.ttf
        - asset: assets/fonts/sometype_mono_italic.ttf
          style: italic
    - family: gaegu
      fonts:
        - asset: assets/fonts/gaegu.ttf
        - asset: assets/fonts/gaegu_bold.ttf
          weight: 700
        - asset: assets/fonts/gaegu_light.ttf
          weight: 300
