name: hueman
description: An open-source game about color theory.
publish_to: "none"

version: 2.2.0+9

environment:
  sdk: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ">=6.2.1"
  rive: ">=0.12.3"
  shared_preferences: ">=2.2.2"
  audioplayers: ">=5.2.1"

dev_dependencies:
  flutter_launcher_icons: ">=0.13.1"
  flutter_test:
    sdk: flutter
  rename: ">=3.0.1"
  flutter_lints: ">=3.0.0"
  msix: ">=3.16.6" # https://pub.dev/packages/msix

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon/iOS_icon.png"
  min_sdk_android: 21
  windows:
    generate: true
    image_path: "assets/app_icon/windows_icon.png"
  macos:
    generate: true
    image_path: "assets/app_icon/mac_icon.png"

msix_config:
  display_name: "HUEman: a game about colors"
  publisher: CN=45439987-713E-4806-A939-727F9EEB2172
  publisher_display_name: Nate Wilson
  identity_name: 56500NateWilson.HUEmanagameaboutcolors
  msix_version: 2.1.0.0
  logo_path: C:\Users\Nate\repos\hueman\assets\app_icon\windows_icon.png
  store: true

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/audio/
    - assets/end_credits_icons/
    - assets/public_domain_photos/
    - assets/

  fonts:
    - family: nunito sans
      fonts:
        - asset: assets/fonts/nunito_sans.ttf
        - asset: assets/fonts/nunito_sans_italic.ttf
          style: italic
    - family: sometype mono
      fonts:
        - asset: assets/fonts/sometype_mono.ttf
        - asset: assets/fonts/sometype_mono_italic.ttf
          style: italic
    - family: gaegu
      fonts:
        - asset: assets/fonts/gaegu.ttf
        - asset: assets/fonts/gaegu_bold.ttf
          weight: 700
        - asset: assets/fonts/gaegu_light.ttf
          weight: 300
#
# `flutter pub deps` output, 17 Dec 2023:
#   Dart SDK 3.2.0
#   Flutter SDK 3.16.0
#   hueman 1.1.0+3
#   |-- audioplayers 5.2.1
#   |   |-- audioplayers_android 4.0.3
#   |   |   |-- audioplayers_platform_interface...
#   |   |   '-- flutter...
#   |   |-- audioplayers_darwin 5.0.2
#   |   |   |-- audioplayers_platform_interface...
#   |   |   '-- flutter...
#   |   |-- audioplayers_linux 3.1.0
#   |   |   |-- audioplayers_platform_interface...
#   |   |   '-- flutter...
#   |   |-- audioplayers_platform_interface 6.1.0
#   |   |   |-- flutter...
#   |   |   |-- meta...
#   |   |   '-- plugin_platform_interface...
#   |   |-- audioplayers_web 4.1.0
#   |   |   |-- js 0.6.7
#   |   |   |   '-- meta...
#   |   |   |-- audioplayers_platform_interface...
#   |   |   |-- flutter...
#   |   |   '-- flutter_web_plugins...
#   |   |-- audioplayers_windows 3.1.0
#   |   |   |-- audioplayers_platform_interface...
#   |   |   '-- flutter...
#   |   |-- file 7.0.0
#   |   |   |-- meta...
#   |   |   '-- path...
#   |   |-- path_provider 2.1.1
#   |   |   |-- path_provider_android 2.2.1
#   |   |   |   |-- flutter...
#   |   |   |   '-- path_provider_platform_interface...
#   |   |   |-- path_provider_foundation 2.3.1
#   |   |   |   |-- flutter...
#   |   |   |   '-- path_provider_platform_interface...
#   |   |   |-- flutter...
#   |   |   |-- path_provider_linux...
#   |   |   |-- path_provider_platform_interface...
#   |   |   '-- path_provider_windows...
#   |   |-- synchronized 3.1.0
#   |   |-- uuid 4.2.1
#   |   |   |-- crypto 3.0.3
#   |   |   |   '-- typed_data...
#   |   |   |-- sprintf 7.0.0
#   |   |   '-- meta...
#   |   |-- flutter...
#   |   |-- http...
#   |   '-- meta...
#   |-- flutter 0.0.0
#   |   |-- characters 1.3.0
#   |   |-- collection 1.18.0
#   |   |-- material_color_utilities 0.5.0
#   |   |   '-- collection...
#   |   |-- meta 1.10.0
#   |   |-- sky_engine 0.0.99
#   |   |-- vector_math 2.1.4
#   |   '-- web 0.3.0
#   |-- flutter_launcher_icons 0.13.1
#   |   |-- args 2.4.2
#   |   |-- checked_yaml 2.0.3
#   |   |   |-- json_annotation...
#   |   |   |-- source_span...
#   |   |   '-- yaml...
#   |   |-- cli_util 0.4.0
#   |   |   |-- meta...
#   |   |   '-- path...
#   |   |-- image 4.1.3
#   |   |   |-- archive 3.4.9
#   |   |   |   |-- pointycastle 3.7.3
#   |   |   |   |   |-- convert 3.1.1
#   |   |   |   |   |   '-- typed_data...
#   |   |   |   |   |-- collection...
#   |   |   |   |   '-- js...
#   |   |   |   |-- crypto...
#   |   |   |   '-- path...
#   |   |   |-- xml 6.4.2
#   |   |   |   |-- petitparser 6.0.1
#   |   |   |   |   '-- meta...
#   |   |   |   |-- collection...
#   |   |   |   '-- meta...
#   |   |   '-- meta...
#   |   |-- json_annotation 4.8.1
#   |   |   '-- meta...
#   |   |-- path 1.8.3
#   |   '-- yaml 3.1.2
#   |       |-- collection...
#   |       |-- source_span...
#   |       '-- string_scanner...
#   |-- flutter_lints 3.0.1
#   |   '-- lints 3.0.0
#   |-- flutter_test 0.0.0
#   |   |-- async 2.11.0
#   |   |   |-- collection...
#   |   |   '-- meta...
#   |   |-- boolean_selector 2.1.1
#   |   |   |-- source_span...
#   |   |   '-- string_scanner...
#   |   |-- clock 1.1.1
#   |   |-- fake_async 1.3.1
#   |   |   |-- clock...
#   |   |   '-- collection...
#   |   |-- matcher 0.12.16
#   |   |   |-- async...
#   |   |   |-- meta...
#   |   |   |-- stack_trace...
#   |   |   |-- term_glyph...
#   |   |   '-- test_api...
#   |   |-- source_span 1.10.0
#   |   |   |-- collection...
#   |   |   |-- path...
#   |   |   '-- term_glyph...
#   |   |-- stack_trace 1.11.1
#   |   |   '-- path...
#   |   |-- stream_channel 2.1.2
#   |   |   '-- async...
#   |   |-- string_scanner 1.2.0
#   |   |   '-- source_span...
#   |   |-- term_glyph 1.2.1
#   |   |-- test_api 0.6.1
#   |   |   |-- async...
#   |   |   |-- boolean_selector...
#   |   |   |-- collection...
#   |   |   |-- meta...
#   |   |   |-- source_span...
#   |   |   |-- stack_trace...
#   |   |   |-- stream_channel...
#   |   |   |-- string_scanner...
#   |   |   '-- term_glyph...
#   |   |-- characters...
#   |   |-- collection...
#   |   |-- flutter...
#   |   |-- material_color_utilities...
#   |   |-- meta...
#   |   |-- path...
#   |   |-- vector_math...
#   |   '-- web...
#   |-- msix 3.16.6
#   |   |-- console 4.1.0
#   |   |   '-- vector_math...
#   |   |-- get_it 7.6.4
#   |   |   |-- async...
#   |   |   '-- collection...
#   |   |-- package_config 2.1.0
#   |   |   '-- path...
#   |   |-- pub_semver 2.1.4
#   |   |   |-- collection...
#   |   |   '-- meta...
#   |   |-- args...
#   |   |-- cli_util...
#   |   |-- image...
#   |   |-- path...
#   |   '-- yaml...
#   |-- rename 3.0.1
#   |   |-- logger 2.0.2+1
#   |   |-- args...
#   |   '-- path...
#   |-- rive 0.12.3
#   |   |-- flutter_web_plugins 0.0.0
#   |   |   |-- characters...
#   |   |   |-- collection...
#   |   |   |-- flutter...
#   |   |   |-- material_color_utilities...
#   |   |   |-- meta...
#   |   |   |-- vector_math...
#   |   |   '-- web...
#   |   |-- http 1.1.0
#   |   |   |-- http_parser 4.0.2
#   |   |   |   |-- typed_data 1.3.2
#   |   |   |   |   '-- collection...
#   |   |   |   |-- collection...
#   |   |   |   |-- source_span...
#   |   |   |   '-- string_scanner...
#   |   |   |-- async...
#   |   |   '-- meta...
#   |   |-- plugin_platform_interface 2.1.7
#   |   |   '-- meta...
#   |   |-- rive_common 0.2.8
#   |   |   |-- ffi 2.1.0
#   |   |   |-- graphs 2.3.1
#   |   |   |   '-- collection...
#   |   |   |-- collection...
#   |   |   |-- flutter...
#   |   |   |-- flutter_web_plugins...
#   |   |   |-- http...
#   |   |   |-- meta...
#   |   |   '-- plugin_platform_interface...
#   |   |-- collection...
#   |   |-- flutter...
#   |   '-- meta...
#   |-- shared_preferences 2.2.2
#   |   |-- shared_preferences_android 2.2.1
#   |   |   |-- flutter...
#   |   |   '-- shared_preferences_platform_interface...
#   |   |-- shared_preferences_foundation 2.3.4
#   |   |   |-- flutter...
#   |   |   '-- shared_preferences_platform_interface...
#   |   |-- shared_preferences_linux 2.3.2
#   |   |   |-- path_provider_linux 2.2.1
#   |   |   |   |-- xdg_directories 1.0.3
#   |   |   |   |   |-- meta...
#   |   |   |   |   '-- path...
#   |   |   |   |-- ffi...
#   |   |   |   |-- flutter...
#   |   |   |   |-- path...
#   |   |   |   '-- path_provider_platform_interface...
#   |   |   |-- path_provider_platform_interface 2.1.1
#   |   |   |   |-- platform 3.1.3
#   |   |   |   |-- flutter...
#   |   |   |   '-- plugin_platform_interface...
#   |   |   |-- file...
#   |   |   |-- flutter...
#   |   |   |-- path...
#   |   |   '-- shared_preferences_platform_interface...
#   |   |-- shared_preferences_platform_interface 2.3.1
#   |   |   |-- flutter...
#   |   |   '-- plugin_platform_interface...
#   |   |-- shared_preferences_web 2.2.2
#   |   |   |-- flutter...
#   |   |   |-- flutter_web_plugins...
#   |   |   |-- shared_preferences_platform_interface...
#   |   |   '-- web...
#   |   |-- shared_preferences_windows 2.3.2
#   |   |   |-- path_provider_windows 2.2.1
#   |   |   |   |-- win32 5.1.0
#   |   |   |   |   '-- ffi...
#   |   |   |   |-- ffi...
#   |   |   |   |-- flutter...
#   |   |   |   |-- path...
#   |   |   |   '-- path_provider_platform_interface...
#   |   |   |-- file...
#   |   |   |-- flutter...
#   |   |   |-- path...
#   |   |   |-- path_provider_platform_interface...
#   |   |   '-- shared_preferences_platform_interface...
#   |   '-- flutter...
#   '-- url_launcher 6.2.1
#       |-- url_launcher_android 6.2.0
#       |   |-- flutter...
#       |   '-- url_launcher_platform_interface...
#       |-- url_launcher_ios 6.2.1
#       |   |-- flutter...
#       |   '-- url_launcher_platform_interface...
#       |-- url_launcher_linux 3.1.0
#       |   |-- flutter...
#       |   '-- url_launcher_platform_interface...
#       |-- url_launcher_macos 3.1.0
#       |   |-- flutter...
#       |   '-- url_launcher_platform_interface...
#       |-- url_launcher_platform_interface 2.2.0
#       |   |-- flutter...
#       |   '-- plugin_platform_interface...
#       |-- url_launcher_web 2.2.1
#       |   |-- flutter...
#       |   |-- flutter_web_plugins...
#       |   |-- url_launcher_platform_interface...
#       |   '-- web...
#       |-- url_launcher_windows 3.1.0
#       |   |-- flutter...
#       |   '-- url_launcher_platform_interface...
#       '-- flutter...
