name: hueman
description: An open-source game about color theory.
publish_to: "none"

version: 2.3.0+13

environment:
  sdk: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ">=6.2.4"
  url_launcher_android: "<6.3.0"
  rive: ">=0.12.4"
  shared_preferences: ">=2.2.2"
  audioplayers: ">=5.2.1"

dev_dependencies:
  flutter_launcher_icons: ">=0.13.1"
  flutter_test:
    sdk: flutter
  rename: ">=3.0.1"
  flutter_lints: ">=3.0.1"
  msix: ">=3.16.7" # https://pub.dev/packages/msix

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon/iOS_icon.png"
  min_sdk_android: 21
  windows:
    generate: true
    image_path: "assets/app_icon/windows_icon.png"
  macos:
    generate: true
    image_path: "assets/app_icon/mac_icon.png"

msix_config:
  display_name: "HUEman: a game about colors"
  publisher: CN=45439987-713E-4806-A939-727F9EEB2172
  publisher_display_name: Nate Wilson
  identity_name: 56500NateWilson.HUEmanagameaboutcolors
  msix_version: 2.3.0.0 # dart run msix:create
  logo_path: C:\Users\Nate\repos\hueman\assets\app_icon\windows_icon.png
  store: true

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/audio/
    - assets/end_credits_icons/
    - assets/public_domain_photos/
    - assets/

  fonts:
    - family: nunito sans
      fonts:
        - asset: assets/fonts/nunito_sans.ttf
        - asset: assets/fonts/nunito_sans_italic.ttf
          style: italic
    - family: sometype mono
      fonts:
        - asset: assets/fonts/sometype_mono.ttf
        - asset: assets/fonts/sometype_mono_italic.ttf
          style: italic
    - family: gaegu
      fonts:
        - asset: assets/fonts/gaegu.ttf
        - asset: assets/fonts/gaegu_bold.ttf
          weight: 700
        - asset: assets/fonts/gaegu_light.ttf
          weight: 300
